version: 2
project_name: jwt-secret-fake-random-goat

builds:
  - env: [ CGO_ENABLED=0 ]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    id: "jwt-secret-fake-random-goat"
    binary: jwt-secret-fake-random-goat
    main: ./main.go

archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
      - goos: linux
        format: tar.gz
      - goos: darwin
        format: tar.gz

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'