project_name: jwt-secret-fake-random-goat
builds:
  - env: [ CGO_ENABLED=0 ]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

    id: "jwt-secret-fake-random-goat"
    binary:
      'jwt-secret-fake-random-goat'

archives:
  - files:
      - none*
    format: zip
    id: homebrew
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: linux
        format: tar.gz